#+setupfile:./hugo_setup.org
#+TITLE: Velocity Obstacles
#+ROAM_KEY: https://ensemble.clemson.edu/hapi/v1/contents/permalinks/MKQVXDFQ/view
#+roam_tags: "Motion Planning"

* Slides
:PROPERTIES:
:NOTER_DOCUMENT: ../slides/velocity_obstacles.pdf
:END:
** From Cartesian to velocity space
:PROPERTIES:
:NOTER_PAGE: 14
:END:
If you take a Cartesian space where agent A is centered and a point. Then B is at position x_{b}-x_{a} and has a radius of r_{a}+r_{b} (because A is a point and the radius has to be inflated).

By doing this you calculate the Minkowski sum. The Minkowsi sum is X \oplus Y = {x + y | x \in X, y \in Y}. So if X is the position of A {[0, 0]}, and Y is the position of B {[1, 1]}. Then X \oplus Y = {[1, 1]}.

** Velocity Space
:PROPERTIES:
:NOTER_PAGE: 15
:END:
If we take that same 2d plane but change the X and Y axis and change them to velocities (by dividing everything by one second).

Now every point in this space denotes a velocity. The question now is what is the set of velocities that will lead to a collision. This is the VO_{A|B}

If we pick some point V_{1} and have it define a ray starting at the origin and going through V_{1} and that ray passes through the disk at some time \tau >= 0 then this is a colliding velocity and is in VO_{A|B}.

** Revising definition
:PROPERTIES:
:NOTER_PAGE: 19
:END:
Lets pick some V. If for any \tau >= 0 V\tau is in the set denoted by the circle with origin at x_{b} - x_{a} with radius r_{a} + r_{b} then it is in the VO_{A|B}.

This leads to the time to collision equation

** Time horizon VO
If you move a disk closer to the origin you can find the time horizon VO.

Given two agents, A and B, the velocity obstacle VO^{\tau_{H}}_{A|B} (read: the velocity obstacle of A induced by B for time horizon \tau_{H}) is the set of all relative velocities that will lead to a collision between A and B at some moment within the next \tau_{H} seconds.

\begin{equation}
VO^{\tau_{H}}_{A|B} = { v | \exists \tau \in [0, \tau_{H}]: \tau V \cap \in D(x_{B} - X_{A}, r_{A} + r_{B}_{}) \ne \emptyset }
\end{equation}

The velocity obstacle VO for time horizon \tau_{H} induced on A by B is equal to all velocities such that a \tau exists between 0 and \tau_{H} (inclusive) such that \tau V unioned with the disk centered at X_{B} - X_{A} with radius r_{A} + r_{B} is not empty.

If a collision happens beyond a certain \tau_{H} it might not matter

Geometrically, this VO is still a cone (assuming circular agents). But this cone is truncated by a disk of radius (r_{A} + r_{B})/\tau_{H} and centered at (x_{A} - x_{B})/\tau_{H} compared to the VO discussed above.

GOT TO 24:40 ish
